In [53]:
# Importing the necessary library.
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [54]:
# Reading the dataset
df = pd.read_csv('/content/customer-segmentation_Anaysis.csv')

In [55]:
# exploring the content in the datasets.
df.head()

,Customer ID,Age,Gender,Marital Status,Education Level,Geographic Information,Occupation,Income Level,Behavioral Data,Purchase History,Interactions with Customer Service,Insurance Products Owned,Coverage Amount,Premium Amount,Policy Type,Customer Preferences,Preferred Communication Channel,Preferred Contact Time,Preferred Language,Segmentation Group
0,84966,23,Female,Married,Associate Degree,Mizoram,Entrepreneur,70541,policy5,04-10-2018,Phone,policy2,366603,2749,Group,Email,In-Person Meeting,Afternoon,English,Segment5
1,95568,26,Male,Widowed,Doctorate,Goa,Manager,54168,policy5,11-06-2018,Chat,policy1,780236,1966,Group,Mail,In-Person Meeting,Morning,French,Segment5
2,10544,29,Female,Single,Associate Degree,Rajasthan,Entrepreneur,73899,policy5,06-05-2021,Email,policy3,773926,4413,Group,Email,Mail,Evening,German,Segment3
3,77033,20,Male,Divorced,Bachelor's Degree,Sikkim,Entrepreneur,63381,policy5,09-02-2018,Chat,policy2,787815,4342,Family,Text,In-Person Meeting,Anytime,French,Segment3
4,88160,25,Female,Separated,Bachelor's Degree,West Bengal,Manager,38794,policy1,09-10-2018,Chat,policy4,366506,1276,Family,Email,Text,Weekends,English,Segment2

In [56]:
#Identifying wheather the datas are stored in the relevant data type
# Purchase History is store object rather than date and time
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53503 entries, 0 to 53502
Data columns (total 20 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Customer ID                         53503 non-null  int64
 1   Age                                 53503 non-null  int64
 2   Gender                              53503 non-null  object
 3   Marital Status                      53503 non-null  object
 4   Education Level                     53503 non-null  object
 5   Geographic Information              53503 non-null  object
 6   Occupation                          53503 non-null  object
 7   Income Level                        53503 non-null  int64
 8   Behavioral Data                     53503 non-null  object
 9   Purchase History                    53503 non-null  object
 10  Interactions with Customer Service  53503 non-null  object
 11  Insurance Products Owned            53503 non-null  object
 12  Coverage Amount                     53503 non-null  int64
 13  Premium Amount                      53503 non-null  int64
 14  Policy Type                         53503 non-null  object
 15  Customer Preferences                53503 non-null  object
 16  Preferred Communication Channel     53503 non-null  object
 17  Preferred Contact Time              53503 non-null  object
 18  Preferred Language                  53503 non-null  object
 19  Segmentation Group                  53503 non-null  object
dtypes: int64(5), object(15)
memory usage: 8.2+ MB

In [57]:
# Idendifing missing values and null values
df.isnull().sum()

Customer ID                           0
Age                                   0
Gender                                0
Marital Status                        0
Education Level                       0
Geographic Information                0
Occupation                            0
Income Level                          0
Behavioral Data                       0
Purchase History                      0
Interactions with Customer Service    0
Insurance Products Owned              0
Coverage Amount                       0
Premium Amount                        0
Policy Type                           0
Customer Preferences                  0
Preferred Communication Channel       0
Preferred Contact Time                0
Preferred Language                    0
Segmentation Group                    0
dtype: int64

In [58]:
# Identifying the presence of duplicated values
# no dupicate values found
df.duplicated().sum()

np.int64(0)

In [59]:
# changing the data type of Purchase History to date time formate for future usage
df['Purchase History'] = df['Purchase History'].str.replace('-','/')

In [60]:
df['Purchase History'] = pd.to_datetime(df['Purchase History'])

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53503 entries, 0 to 53502
Data columns (total 20 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Customer ID                         53503 non-null  int64
 1   Age                                 53503 non-null  int64
 2   Gender                              53503 non-null  object
 3   Marital Status                      53503 non-null  object
 4   Education Level                     53503 non-null  object
 5   Geographic Information              53503 non-null  object
 6   Occupation                          53503 non-null  object
 7   Income Level                        53503 non-null  int64
 8   Behavioral Data                     53503 non-null  object
 9   Purchase History                    53503 non-null  datetime64[ns]
 10  Interactions with Customer Service  53503 non-null  object
 11  Insurance Products Owned            53503 non-null  object
 12  Coverage Amount                     53503 non-null  int64
 13  Premium Amount                      53503 non-null  int64
 14  Policy Type                         53503 non-null  object
 15  Customer Preferences                53503 non-null  object
 16  Preferred Communication Channel     53503 non-null  object
 17  Preferred Contact Time              53503 non-null  object
 18  Preferred Language                  53503 non-null  object
 19  Segmentation Group                  53503 non-null  object
dtypes: datetime64[ns](1), int64(5), object(14)
memory usage: 8.2+ MB

In [62]:
#renamimg all columns names into lower case
df.columns = df.columns.str.lower()

In [63]:
# Removing the space inbetween the columns name
df.columns = df.columns.str.replace(' ','_')